# Generated by Django 5.0.6 on 2024-05-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogkul', '0003_rename_comment_comment1_like1_delete_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='likes',
            field=models.ManyToManyField(related_name='publications', to='blogkul.like1'),
        ),
    ]
