# Generated by Django 5.0.6 on 2024-05-21 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogkul', '0004_publication_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment1',
            options={},
        ),
        migrations.RenameField(
            model_name='comment1',
            old_name='created_at',
            new_name='cdate',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='likes',
        ),
        migrations.AlterField(
            model_name='comment1',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogkul.publication'),
        ),
        migrations.AlterField(
            model_name='comment1',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publication',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='publication',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='publication',
            name='pdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
