# Generated by Django 5.0.6 on 2024-05-28 15:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogkul', '0005_alter_comment1_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment1',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='Like1',
            new_name='Like',
        ),
    ]
