# Generated by Django 5.0.6 on 2024-06-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogkul', '0006_rename_comment1_comment_rename_like1_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='publication_images/'),
        ),
    ]
