# Generated by Django 5.0.6 on 2024-06-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogkul', '0007_publication_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='image',
            field=models.ImageField(default='publication_images/def.png', upload_to='publication_images/'),
        ),
    ]
