# Generated by Django 5.0.6 on 2024-06-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogkul', '0009_publication_author_publication_is_private_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='is_private',
        ),
        migrations.AddField(
            model_name='publication',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='publication_images/'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='publication',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='publication',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
