# Generated by Django 5.0.6 on 2024-06-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogkul', '0010_remove_publication_is_private_publication_is_public_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='author',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='like_count',
        ),
        migrations.AddField(
            model_name='publication',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='publication',
            name='image',
            field=models.ImageField(default='publication_images/def.png', upload_to='publication_images/'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
